// skill/image-particle-fx/assets/components/ParticleImage.jsx
// React wrapper for the ParticleFX engine.
// Setup: copy assets/fx/ into your project (e.g. src/fx/), `npm i three`, then:
//   <ParticleImage src="/hero.jpg" effect="silk" progress={scrollProgress} style={{ height: '100vh' }} />
// - `progress` given  -> controlled: 0 = image formed, 1 = dissolved (e.g. bind to scroll / hover).
// - `progress` absent -> plays `timeline` (or the default hold → dissolve → reform loop).
import { useEffect, useRef } from 'react';
import { ParticleFX } from '../fx/index.js'; // adjust to where you copied fx/

export default function ParticleImage({
    src, morphTo, effect = 'fluid-erosion', params, look, camera, timeline, quality = 'high',
    depth, progress, interactive = true, onLoaded, className, style,
}) {
    const host = useRef(null);
    const fx = useRef(null);

    // (re)build when the image or quality changes
    useEffect(() => {
        const engine = new ParticleFX(host.current, { interactive });
        fx.current = engine;
        let alive = true;
        engine.load({ image: src, morphTo, effect, params, look, camera, timeline, quality, depth })
            .then(info => { if (!alive) return; if (progress != null) engine.setProgress(progress, true); engine.start(); onLoaded?.(info); })
            .catch(err => console.error('[ParticleImage]', err));
        return () => { alive = false; engine.dispose(); fx.current = null; };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [src, morphTo, quality, interactive]);

    // cheap live updates
    useEffect(() => { if (fx.current?.points) fx.current.setEffect(effect, params || {}); }, [effect, JSON.stringify(params)]);
    useEffect(() => { if (fx.current?.points) fx.current.setLook(look || {}); }, [JSON.stringify(look)]);
    useEffect(() => { if (fx.current?.points) fx.current.setCamera(camera || {}); }, [JSON.stringify(camera)]);
    useEffect(() => { if (fx.current?.points && timeline) fx.current.setTimeline(timeline); }, [JSON.stringify(timeline)]);
    useEffect(() => {
        const e = fx.current; if (!e) return;
        if (progress == null) e.play(); else e.setProgress(progress);
    }, [progress]);

    return <div ref={host} className={className} style={{ position: 'relative', width: '100%', height: '100%', overflow: 'hidden', ...style }} />;
}

// skill/image-particle-fx/assets/components/ParticleImage.vue
<!--
  Vue 3 wrapper for the ParticleFX engine.
  Setup: copy assets/fx/ into your project (e.g. src/fx/), `npm i three`, then:
    <ParticleImage src="/hero.jpg" effect="ember-ascend" :progress="scrollProgress" style="height:100vh" />
  progress given -> controlled (0 formed, 1 dissolved); absent -> plays the timeline loop.
-->
<template>
  <div ref="host" class="particle-image" />
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { ParticleFX } from '../fx/index.js'; // adjust to where you copied fx/

const props = defineProps({
  src: { type: String, required: true },
  morphTo: String,
  effect: { type: String, default: 'fluid-erosion' },
  params: Object, look: Object, camera: Object, timeline: Object, depth: Object,
  quality: { type: String, default: 'high' },
  progress: { type: Number, default: null },
  interactive: { type: Boolean, default: true },
});
const emit = defineEmits(['loaded']);
const host = ref(null);
let fx = null;

async function build() {
  fx?.dispose();
  fx = new ParticleFX(host.value, { interactive: props.interactive });
  const info = await fx.load({
    image: props.src, morphTo: props.morphTo, effect: props.effect, params: props.params, look: props.look,
    camera: props.camera, timeline: props.timeline, quality: props.quality, depth: props.depth,
  });
  if (props.progress != null) fx.setProgress(props.progress, true);
  fx.start();
  emit('loaded', info);
}

onMounted(build);
onBeforeUnmount(() => { fx?.dispose(); fx = null; });
watch(() => [props.src, props.morphTo, props.quality], build);
watch(() => [props.effect, JSON.stringify(props.params)], () => fx?.points && fx.setEffect(props.effect, props.params || {}));
watch(() => JSON.stringify(props.look), () => fx?.points && fx.setLook(props.look || {}));
watch(() => JSON.stringify(props.camera), () => fx?.points && fx.setCamera(props.camera || {}));
watch(() => props.progress, (p) => { if (!fx) return; if (p == null) fx.play(); else fx.setProgress(p); });
</script>

<style scoped>
.particle-image { position: relative; width: 100%; height: 100%; overflow: hidden; }
</style>
